### ISSUE TITLE
멀티 모듈 프로젝트 세팅의 의도

### ISSUE THREAD

**Issue by djkeh** [bloodfinger8/fcPay-mission#3]
이 프로젝트는 루트 디렉토리에 바로 프로젝트 소스코드가 보편적인 형태로(`~/src`) 위치하지 않고, `~/payment-service` 프로젝트 디렉토리 안에 위치하고 있습니다.
또한 노션 문서를 보면 멀티 모듈로 구성하는 방법이 궁금하다는 질문이 올라와 있습니다.
이 프로젝트가 이렇게 구성된 이유가 무엇인지 궁금하네요.

## Reference

* https://www.notion.so/2023-2-aa29e2a180d94bbb8584cc2c9d979d33?pvs=4#97fab7eeb79f469c94b6e6fa1ae22eba

**Comment by bloodfinger8** [comment]
@djkeh 

사실 처음부터 멀티모듈 형태의 구성을 염두하고 있었습니다.
그래서 최초의 payment-service부터 시작해서 여러 서비스를 구성하려고 했는데 아직 도메인의 숙련도가 없는 상태에서 제 생각대로 자잘자잘하게 도메인이나 기능들을 분리하는게 맞는지 의문이 들었습니다.

또한 기능 별로 모듈을 분리하기 시작하면 자칫 모듈간의 의존성들이 꼬이게 될꺼같아서 일단은 단일 모듈로 구성하게 되었습니다.
