### ISSUE TITLE
프로젝트를 Intellij로 열고 사용하면 원치 않는 파일이 생성되는 문제

### ISSUE THREAD

**Issue by djkeh** [bloodfinger8/fcPay-mission#5]
<img width="927" alt="image" src="https://github.com/bloodfinger8/fcPay-mission/assets/4949544/3fc8f38e-1459-409e-b75b-37b2b67f9001">

위 스크린샷과 같이 프로젝트를 intellij 에서 열고 앱을 실행하거나 테스트 등을 수행하면
원치 않는 파일들이 숨겨진 디렉토리 안에 만들어집니다.

1. 이 파일들은 각각 무엇인지,
2. 반드시 프로젝트에 필요한 것인지,
3. 만약 필요하다면 깃헙 프로젝트에는 포함되어있지 않은 이유가 무엇인지,
4. 만약 필요 없다면 이렇게 만들어지거나 깃 변경점에 잡히지 않도록 하려면 어떻게 해야 하는지

궁금합니다.

**Comment by bloodfinger8** [comment]
gitignore.io 를 이용해 좀 더 신뢰할 수 있는 .gitignore 만들기 #6 

처리 완료
